export const opcionesGenero = ['Femenino', 'Masculino', 'Prefiero no decirlo']

export const opcionesOcupacion = [
    'Abogado',
    'Administrador de empresas',
    'Ama de casa',
    'Analista financiero',
    'Arquitecto',
    'Asistente de gerencia',
    'Chef o cocinero',
    'Chofer de transporte',
    'Consultor de negocios',
    'Contador público',
    'Diseñador',
    'Docente',
    'Ejecutivo de ventas',
    'Empleado bancario',
    'Empleado de comercio',
    'Empleado de escribanía',
    'Empleado público',
    'Escribano',
    'Farmacéutico',
    'Ingeniero',
    'Marketing y Publicidad',
    'Médico',
    'Operario de fábrica',
    'Periodista',
    'Personal de limpieza',
    'Profesor o maestro',
    'Programador informático',
    'Psicólogo',
    'Recursos humanos',
    'Seguridad',
    'Técnico en informática',
    'Trabajador administrativo',
    'Trabajador de la construcción',
    'Trabajador de la salud',
    'Trabajador social',
    'Veterinario'
]

export const opcionesProvincia = [
    'CABA',
    'Buenos Aires',
    'Catamarca',
    'Chaco',
    'Chubut',
    'Cordoba',
    'Corrientes',
    'Entre Rios',
    'Formosa',
    'Jujuy',
    'La Pampa',
    'La Rioja',
    'Mendoza',
    'Misiones',
    'Neuquén',
    'Rio Negro',
    'Salta',
    'San Juan',
    'San Luis',
    'Santa Cruz',
    'Santa Fe',
    'Santiago del Estero',
    'Tierra del Fuego',
    'Tucuman'
]

export const opcionesCiudades = [
    'Villa La Angostura'
]
